const [permissions, setPermissions] = useState({
    dashboard: {
      all: false,
      subModules: {
        mainDashboard: { view: false, edit: false, delete: false, all: false },
        GLDashboard: { view: false, edit: false, delete: false, all: false },
        inventoryDashboard: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchasedDashboard: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        logisticsDashboard: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
      },
    },
    generalLedger: {
      all: false,
      subModules: {
        showroomManager: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        costAndProfit: { view: false, edit: false, delete: false, all: false },
        chartOfAccount: { view: false, edit: false, delete: false, all: false },
        currencyManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        subsidiaryLedger: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        voucherSetup: { view: false, edit: false, delete: false, all: false },
        subsidiaryFileSetup: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        bankDetails: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        cashAccountDetails: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        creditAccountDetails: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        financialYearList: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        openingBalance: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        openingBalanceVoucher: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        internalCashTransfer: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        accountListingReport: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        searchingVoucher: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        generalLedger: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        subsidiaryGeneralLedger: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        trialBalance: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        profitAndLoss: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        balanceSheet: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
      },
    },
    inventory: {
      all: false,
      subModules: {
        searchVehcile: { view: false, edit: false, delete: false, all: false },
        listView: { view: false, edit: false, delete: false, all: false },
        gridView: { view: false, edit: false, delete: false, all: false },
        addStock: { view: false, edit: false, delete: false, all: false },
        zoneSetup: { view: false, edit: false, delete: false, all: false },
        parkingZoneManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        vehicleTransferTo: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        vehicleTransferManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        incomingVehicle: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        vehicleRepairDetails: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        vehicleRepairManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        repairVoucherManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        roadTestForm: { view: false, edit: false, delete: false, all: false },
        roadTestRecord: { view: false, edit: false, delete: false, all: false },
        logBook: { view: false, edit: false, delete: false, all: false },
      },
    },
    sales: {
      all: false,
      subModules: {
        saleDead: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        cashSaleList: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        creditSaleList: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        commission: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        gatepassForm: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        gatepassRecord: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        marketTrendAnalysis: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
      },
    },
    purchase: {
      all: false,
      subModules: {
        purchaseRequisition: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        quotationDocument: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        tenderDocument: { view: false, edit: false, delete: false, all: false },
        comparativeStatement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchaseOrder: { view: false, edit: false, delete: false, all: false },
        goodRecievedNote: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        payment: { view: false, edit: false, delete: false, all: false },
        transportation: { view: false, edit: false, delete: false, all: false },
        expenseManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        expenseSheet: { view: false, edit: false, delete: false, all: false },
        purchaseReturnRequest: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchasedDispatchedNote: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchasedReturnNote: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        payableConfiguration: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchasedReturnVOucher: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchasedAndPayableReturnVoucher: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        paymentVoucher: { view: false, edit: false, delete: false, all: false },
        advanceReturnVoucher: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchasedOrderReport: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        purchaseShowroomWiseReport: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        paymentRegisterReport: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        payableAgingReport: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        pendingPOItems: { view: false, edit: false, delete: false, all: false },
        supplierContactList: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        unpaidSupplierBill: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        supplierWiseBillReports: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
      },
    },
    logistics: {
      all: false,
      subModules: {
        wayToYard: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        inYard: { view: false, edit: false, delete: false, all: false },
        loadPlaining: { view: false, edit: false, delete: false, all: false },
        arriving: { view: false, edit: false, delete: false, all: false },
        shipped: { view: false, edit: false, delete: false, all: false },
        vehicleLoaded: { view: false, edit: false, delete: false, all: false },
      },
    },
    auction: {
      all: false,
      subModules: {
        auctionHouse: { view: false, edit: false, delete: false, all: false },
        auctionGridView: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
        priceChecker: { view: false, edit: false, delete: false, all: false },
        dutyChecker: { view: false, edit: false, delete: false, all: false },
      },
    },
    quotation: {
      all: false,
      subModules: {
        quotationDocuments: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
      },
    },
    branding: {
      all: false,
      subModules: {
        branding: { view: false, edit: false, delete: false, all: false },
      },
    },
    users: {
      all: false,
      subModules: {
        userManagement: { view: false, edit: false, delete: false, all: false },
        roleManagement: { view: false, edit: false, delete: false, all: false },
        permissionManagement: {
          view: false,
          edit: false,
          delete: false,
          all: false,
        },
      },
    },
  });